"""Odoo connector — orchestration only.

All HTTP / JSON-RPC calls → client/http_client.py
All retry logic          → helpers/utils.py
All record normalization → helpers/normalizer.py
All exception types      → exceptions.py

The connector class exposes thirteen async methods that map onto the most-used
Odoo ORM models — ``res.partner``, ``crm.lead``, ``sale.order``,
``account.move``, ``product.template``, ``project.task``, ``hr.employee``,
``stock.picking`` — plus a generic :meth:`execute_method` escape hatch that
lets advanced callers reach any model/method without modifying the connector
source (OCP).

Auth: API key. The key replaces the user password in every JSON-RPC call —
Odoo blocks JSON-RPC logins that present a password when 2FA is enabled, so
the API key is the only universally safe credential.
"""
from datetime import datetime
from typing import Any, Dict, List, Optional

import structlog
from shared.base_connector import (
    AuthStatus,
    BaseConnector,
    ConnectorHealth,
    ConnectorStatus,
    NormalizedDocument,
    SyncResult,
    SyncStatus,
    TokenInfo,
)

from client.http_client import OdooHTTPClient
from exceptions import (
    OdooAccessError,
    OdooAuthError,
    OdooError,
    OdooNetworkError,
    OdooNotFoundError,
)
from helpers.normalizer import normalize_partner
from helpers.utils import with_retry

logger = structlog.get_logger(__name__)

_DEFAULT_RATE_LIMIT_PER_MIN = 60


class OdooConnector(BaseConnector):
    """Shielva connector for the Odoo ERP/CRM platform.

    Authentication uses Odoo's per-user API keys (generated by the end user
    from *Preferences → Account Security → API Keys*). The connector targets
    a tenant-specific ``base_url`` and database, so the same class supports
    both Odoo.com SaaS instances and self-hosted deployments.
    """

    CONNECTOR_TYPE: str = "odoo"
    CONNECTOR_NAME: str = "Odoo"
    AUTH_TYPE: str = "api_key"

    REQUIRED_CONFIG_KEYS: List[str] = [
        "base_url",
        "db",
        "username",
        "api_key",
    ]

    # OCP — HTTP status → (ConnectorHealth, AuthStatus) classification.
    _STATUS_MAP: Dict[int, Any] = {
        401: ("OFFLINE", "TOKEN_EXPIRED"),
        403: ("UNHEALTHY", "INVALID_CREDENTIALS"),
        429: ("DEGRADED", "CONNECTED"),
    }

    def __init__(
        self,
        tenant_id: str = "",
        connector_id: str = "",
        config: Optional[Dict[str, Any]] = None,
    ) -> None:
        super().__init__(tenant_id, connector_id, config)
        # Accept either ``base_url`` (canonical) or legacy ``instance_url``.
        base_url = (self.config.get("base_url") or self.config.get("instance_url") or "")
        self.base_url: str = base_url.rstrip("/")
        self.db: str = self.config.get("db", "") or ""
        self.username: str = self.config.get("username", "") or ""
        self.api_key: str = self.config.get("api_key", "") or ""

        try:
            self.rate_limit_per_min: int = int(
                self.config.get("rate_limit_per_min") or _DEFAULT_RATE_LIMIT_PER_MIN
            )
        except (TypeError, ValueError):
            self.rate_limit_per_min = _DEFAULT_RATE_LIMIT_PER_MIN

        self.http_client: OdooHTTPClient = OdooHTTPClient(
            base_url=self.base_url,
            db=self.db,
            username=self.username,
            api_key=self.api_key,
        )

    # ── Internal helpers ──────────────────────────────────────────────────

    def _missing_credentials(self) -> List[str]:
        missing: List[str] = []
        for key in self.REQUIRED_CONFIG_KEYS:
            attr = "base_url" if key == "base_url" else key
            if not getattr(self, attr, ""):
                missing.append(key)
        return missing

    # ── BaseConnector abstract surface ────────────────────────────────────

    async def install(self) -> ConnectorStatus:
        """Validate install-time config and authenticate against Odoo.

        Calls ``common.authenticate`` — a successful call proves the URL,
        database name, username and API key are all consistent.
        """
        missing = self._missing_credentials()
        if missing:
            logger.warning(
                "odoo.install.missing_credentials",
                connector_id=self.connector_id,
                missing=missing,
            )
            return ConnectorStatus(
                connector_id=self.connector_id,
                health=ConnectorHealth.OFFLINE,
                auth_status=AuthStatus.MISSING_CREDENTIALS,
                message=f"Missing required fields: {', '.join(missing)}",
            )

        try:
            uid = await with_retry(self.http_client.authenticate, max_retries=2)
        except OdooAuthError as exc:
            logger.warning(
                "odoo.install.invalid_credentials",
                connector_id=self.connector_id,
                error=str(exc),
            )
            return ConnectorStatus(
                connector_id=self.connector_id,
                health=ConnectorHealth.UNHEALTHY,
                auth_status=AuthStatus.INVALID_CREDENTIALS,
                message=str(exc),
            )
        except OdooNetworkError as exc:
            logger.warning(
                "odoo.install.network_error",
                connector_id=self.connector_id,
                error=str(exc),
            )
            return ConnectorStatus(
                connector_id=self.connector_id,
                health=ConnectorHealth.OFFLINE,
                auth_status=AuthStatus.CONNECTED,
                message=f"Could not reach Odoo instance: {exc}",
            )
        except OdooError as exc:
            logger.warning(
                "odoo.install.rpc_error",
                connector_id=self.connector_id,
                error=str(exc),
            )
            return ConnectorStatus(
                connector_id=self.connector_id,
                health=ConnectorHealth.UNHEALTHY,
                auth_status=AuthStatus.FAILED,
                message=str(exc),
            )

        await self.save_config(
            {
                "base_url": self.base_url,
                "db": self.db,
                "username": self.username,
                "api_key": self.api_key,
                "rate_limit_per_min": self.rate_limit_per_min,
            }
        )
        logger.info(
            "odoo.install.ok",
            connector_id=self.connector_id,
            uid=uid,
        )
        return ConnectorStatus(
            connector_id=self.connector_id,
            health=ConnectorHealth.HEALTHY,
            auth_status=AuthStatus.AUTHENTICATED,
            message=f"Connected to Odoo as uid={uid}",
            metadata={"uid": uid, "db": self.db, "base_url": self.base_url},
        )

    async def authorize(self, auth_code: str = "", state: str = "") -> TokenInfo:
        """API-key connector — no OAuth code exchange.

        Returned for surface compatibility with the BaseConnector ABI: a
        TokenInfo whose access_token is the configured api_key.
        """
        return TokenInfo(
            access_token=self.api_key,
            refresh_token=None,
            expires_at=None,
            token_type="api_key",
            scopes=[],
        )

    async def health_check(self) -> ConnectorStatus:
        """Verify Odoo connectivity by re-authenticating.

        Forces a fresh authenticate round-trip (no uid cache) so a revoked
        API key surfaces immediately.
        """
        missing = self._missing_credentials()
        if missing:
            return ConnectorStatus(
                connector_id=self.connector_id,
                health=ConnectorHealth.OFFLINE,
                auth_status=AuthStatus.MISSING_CREDENTIALS,
                message=f"Missing required fields: {', '.join(missing)}",
            )

        self.http_client.clear_uid_cache()
        try:
            uid = await with_retry(self.http_client.authenticate, max_retries=2)
        except OdooAuthError as exc:
            logger.warning(
                "odoo.health.token_expired",
                connector_id=self.connector_id,
                error=str(exc),
            )
            return ConnectorStatus(
                connector_id=self.connector_id,
                health=ConnectorHealth.DEGRADED,
                auth_status=AuthStatus.TOKEN_EXPIRED,
                message=f"Odoo auth failed: {exc}",
            )
        except OdooNetworkError as exc:
            return ConnectorStatus(
                connector_id=self.connector_id,
                health=ConnectorHealth.OFFLINE,
                auth_status=AuthStatus.CONNECTED,
                message=f"Odoo unreachable: {exc}",
            )
        except OdooError as exc:
            return ConnectorStatus(
                connector_id=self.connector_id,
                health=ConnectorHealth.DEGRADED,
                auth_status=AuthStatus.CONNECTED,
                message=str(exc),
            )

        return ConnectorStatus(
            connector_id=self.connector_id,
            health=ConnectorHealth.HEALTHY,
            auth_status=AuthStatus.CONNECTED,
            message=f"Odoo reachable. Authenticated as uid={uid}",
            metadata={"uid": uid, "db": self.db, "base_url": self.base_url},
        )

    async def sync(
        self,
        since: Optional[datetime] = None,
        full: bool = False,
        kb_id: Optional[str] = None,
        webhook_url: Optional[str] = None,
        page_size: int = 100,
    ) -> SyncResult:
        """Sync ``res.partner`` records into the Shielva knowledge base.

        Pages through every accessible partner, normalizes each into a
        :class:`NormalizedDocument` and hands it off via
        :meth:`ingest_document`. Returns canonical :class:`SyncResult`.
        """
        _ = since, full, webhook_url
        offset = 0
        found = 0
        synced = 0
        failed = 0
        errors: List[str] = []

        try:
            while True:
                page = await self.list_partners(limit=page_size, offset=offset)
                if not page:
                    break
                found += len(page)
                for record in page:
                    try:
                        doc: NormalizedDocument = normalize_partner(
                            record,
                            connector_id=self.connector_id,
                            tenant_id=self.tenant_id,
                            base_url=self.base_url,
                        )
                        await self.ingest_document(
                            doc,
                            kb_id=kb_id or "",
                            webhook_url=webhook_url,
                        )
                        synced += 1
                    except Exception as exc:  # noqa: BLE001
                        failed += 1
                        errors.append(str(exc))
                        logger.error(
                            "odoo.sync.partner_failed",
                            error=str(exc),
                            connector_id=self.connector_id,
                        )
                if len(page) < page_size:
                    break
                offset += page_size
        except OdooError as exc:
            logger.error(
                "odoo.sync.failed",
                error=str(exc),
                connector_id=self.connector_id,
            )
            return SyncResult(
                status=SyncStatus.FAILED,
                connector_id=self.connector_id,
                documents_found=found,
                documents_synced=synced,
                documents_failed=failed,
                errors=errors + [str(exc)],
                message=str(exc),
            )

        status = SyncStatus.COMPLETED if failed == 0 else SyncStatus.PARTIAL
        return SyncResult(
            status=status,
            connector_id=self.connector_id,
            documents_found=found,
            documents_synced=synced,
            documents_failed=failed,
            errors=errors,
            message=f"Synced {synced}/{found} Odoo partners",
        )

    # ── Partners (res.partner) ────────────────────────────────────────────

    async def list_partners(
        self,
        limit: int = 50,
        offset: int = 0,
        domain: Optional[List[Any]] = None,
        fields: Optional[List[str]] = None,
    ) -> List[Dict[str, Any]]:
        """Return ``res.partner`` records via ``search_read``.

        ``domain`` is an Odoo search domain (e.g.
        ``[("is_company", "=", True)]``). ``fields`` restricts the returned
        columns; pass ``None`` to receive Odoo's default field set.
        """
        kwargs: Dict[str, Any] = {"limit": int(limit), "offset": int(offset)}
        if fields:
            kwargs["fields"] = list(fields)
        return await with_retry(
            self.http_client.execute_kw,
            "res.partner",
            "search_read",
            [list(domain or [])],
            kwargs,
        )

    async def get_partner(
        self,
        partner_id: int,
        fields: Optional[List[str]] = None,
    ) -> Dict[str, Any]:
        """Return a single ``res.partner`` record (``read`` semantics).

        Odoo's ``read([id])`` returns a list of dicts; this helper unwraps it
        to a single dict (or an empty dict when the id does not exist).
        """
        kwargs: Dict[str, Any] = {}
        if fields:
            kwargs["fields"] = list(fields)
        result = await with_retry(
            self.http_client.execute_kw,
            "res.partner",
            "read",
            [[int(partner_id)]],
            kwargs,
        )
        if isinstance(result, list) and result:
            return result[0]
        return {}

    async def create_partner(
        self,
        name: str,
        email: Optional[str] = None,
        phone: Optional[str] = None,
        is_company: bool = False,
    ) -> int:
        """Create a ``res.partner`` and return the new record id."""
        if not name:
            raise ValueError("name is required")
        values: Dict[str, Any] = {"name": name, "is_company": bool(is_company)}
        if email:
            values["email"] = email
        if phone:
            values["phone"] = phone
        return await with_retry(
            self.http_client.execute_kw,
            "res.partner",
            "create",
            [values],
            {},
        )

    async def update_partner(
        self,
        partner_id: int,
        fields: Dict[str, Any],
    ) -> bool:
        """Update a ``res.partner`` and return Odoo's ``True``/``False`` ack."""
        if not fields:
            raise ValueError("fields dict must be non-empty")
        return await with_retry(
            self.http_client.execute_kw,
            "res.partner",
            "write",
            [[int(partner_id)], dict(fields)],
            {},
        )

    async def delete_partner(self, partner_id: int) -> bool:
        """Delete (unlink) a ``res.partner`` and return the ack."""
        return await with_retry(
            self.http_client.execute_kw,
            "res.partner",
            "unlink",
            [[int(partner_id)]],
            {},
        )

    # ── CRM (crm.lead) ────────────────────────────────────────────────────

    async def list_leads(
        self,
        limit: int = 50,
        offset: int = 0,
        domain: Optional[List[Any]] = None,
    ) -> List[Dict[str, Any]]:
        """Return ``crm.lead`` records via ``search_read``."""
        return await with_retry(
            self.http_client.execute_kw,
            "crm.lead",
            "search_read",
            [list(domain or [])],
            {"limit": int(limit), "offset": int(offset)},
        )

    async def create_lead(
        self,
        name: str,
        partner_id: Optional[int] = None,
        email_from: Optional[str] = None,
        expected_revenue: float = 0,
    ) -> int:
        """Create a ``crm.lead`` and return the new lead id."""
        if not name:
            raise ValueError("name is required")
        values: Dict[str, Any] = {
            "name": name,
            "expected_revenue": float(expected_revenue or 0),
        }
        if partner_id is not None:
            values["partner_id"] = int(partner_id)
        if email_from:
            values["email_from"] = email_from
        return await with_retry(
            self.http_client.execute_kw,
            "crm.lead",
            "create",
            [values],
            {},
        )

    # ── Sales (sale.order) ────────────────────────────────────────────────

    async def list_sale_orders(
        self,
        limit: int = 50,
        offset: int = 0,
        domain: Optional[List[Any]] = None,
    ) -> List[Dict[str, Any]]:
        """Return ``sale.order`` records via ``search_read``."""
        return await with_retry(
            self.http_client.execute_kw,
            "sale.order",
            "search_read",
            [list(domain or [])],
            {"limit": int(limit), "offset": int(offset)},
        )

    # ── Invoices (account.move, move_type=out_invoice) ────────────────────

    async def list_invoices(
        self,
        limit: int = 50,
        offset: int = 0,
    ) -> List[Dict[str, Any]]:
        """Return customer invoices via ``account.move`` ``search_read``."""
        return await with_retry(
            self.http_client.execute_kw,
            "account.move",
            "search_read",
            [[("move_type", "=", "out_invoice")]],
            {"limit": int(limit), "offset": int(offset)},
        )

    # ── Products (product.template) ───────────────────────────────────────

    async def list_products(
        self,
        limit: int = 50,
        offset: int = 0,
        domain: Optional[List[Any]] = None,
    ) -> List[Dict[str, Any]]:
        """Return ``product.template`` records via ``search_read``."""
        return await with_retry(
            self.http_client.execute_kw,
            "product.template",
            "search_read",
            [list(domain or [])],
            {"limit": int(limit), "offset": int(offset)},
        )

    # ── Projects (project.task) ───────────────────────────────────────────

    async def list_tasks(
        self,
        limit: int = 50,
        offset: int = 0,
        domain: Optional[List[Any]] = None,
    ) -> List[Dict[str, Any]]:
        """Return ``project.task`` records via ``search_read``."""
        return await with_retry(
            self.http_client.execute_kw,
            "project.task",
            "search_read",
            [list(domain or [])],
            {"limit": int(limit), "offset": int(offset)},
        )

    # ── HR (hr.employee) ──────────────────────────────────────────────────

    async def list_employees(
        self,
        limit: int = 50,
        offset: int = 0,
        domain: Optional[List[Any]] = None,
    ) -> List[Dict[str, Any]]:
        """Return ``hr.employee`` records via ``search_read``."""
        return await with_retry(
            self.http_client.execute_kw,
            "hr.employee",
            "search_read",
            [list(domain or [])],
            {"limit": int(limit), "offset": int(offset)},
        )

    # ── Inventory (stock.picking) ─────────────────────────────────────────

    async def list_pickings(
        self,
        limit: int = 50,
        offset: int = 0,
        domain: Optional[List[Any]] = None,
    ) -> List[Dict[str, Any]]:
        """Return ``stock.picking`` records via ``search_read``."""
        return await with_retry(
            self.http_client.execute_kw,
            "stock.picking",
            "search_read",
            [list(domain or [])],
            {"limit": int(limit), "offset": int(offset)},
        )

    # ── Generic escape hatch ──────────────────────────────────────────────

    async def execute_method(
        self,
        model: str,
        method: str,
        args: Optional[List[Any]] = None,
        kwargs: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Call any Odoo model method via ``execute_kw``.

        OCP-friendly escape hatch: callers can reach any Odoo model
        (``account.payment``, ``hr.leave``, ``mail.message`` …) without
        modifying this connector. Adding domain-specific helpers above
        remains preferred when the model is used by ≥ 2 callers.
        """
        if not model or not method:
            raise ValueError("model and method are required")
        return await with_retry(
            self.http_client.execute_kw,
            model,
            method,
            list(args or []),
            dict(kwargs or {}),
        )

    # ── Lifecycle ─────────────────────────────────────────────────────────

    async def aclose(self) -> None:
        """Release any cached state held by the HTTP client."""
        self.http_client.clear_uid_cache()

    async def __aenter__(self) -> "OdooConnector":
        return self

    async def __aexit__(self, *_: object) -> None:
        await self.aclose()
